# K Fold

- Código Versão 1.0 - 18 SET 23

- Esse caderno tem o objetivo de separar o dataset em partições, com a finalidade de executar os testes.

- A tentativa de execução direta, utilizando um laço for, não obteve o resultado esperado, uma vez que gerou erro de memória.

- Amostragem estratificada, **kfold**.
- Semente 42.
- K = 5.

## Bibliotecas

In [2]:
!pip install -q -U watermark

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 16.9 MB/s eta 0:00:00

In [3]:
from sklearn.model_selection import StratifiedKFold

In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pylab import rcParams

In [5]:
%matplotlib inline
%config InlineBackend.figure_format='retina'

sns.set(style='whitegrid', palette='muted', font_scale=1.2)

HAPPY_COLORS_PALETTE = ["#01BEFE", "#FFDD00", "#FF7D00", "#FF006D", "#ADFF02", "#8F00FF"]

sns.set_palette(sns.color_palette(HAPPY_COLORS_PALETTE))

rcParams['figure.figsize'] = 12, 8

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

In [7]:
%reload_ext watermark
%watermark -v -p numpy,pandas,torch,sklearn

Python implementation: CPython
Python version       : 3.10.12
IPython version      : 7.34.0

numpy  : 1.23.5
pandas : 1.5.3
torch  : 2.0.1+cu118
sklearn: 1.2.2

## Importando o dataset

In [8]:
df = pd.read_csv('dataset.csv')

In [9]:
n=5
kf = StratifiedKFold(n_splits=n, random_state=RANDOM_SEED, shuffle=True)

In [29]:
i=0
kfold_manual_train = []
kfold_manual_test = []
for index_df_train, index_df_test in kf.split(df['resumo'],df['rotulo']):
    i=i+1
    kfold_manual_train.append(index_df_train)
    kfold_manual_test.append(index_df_test)
    print("*"*12)
    print("Esse é o " + str(i) + " fold")
    print()
    print("index_df_train: "+ str(index_df_train))
    print()
    print("index_df_test: "+ str(index_df_test))

************
Esse é o 1 fold

index_df_train: [  0   1   2   3   5   6   7   8  10  11  12  13  15  16  18  21  23  24
  25  27  28  29  30  31  32  33  34  35  37  38  39  40  41  42  43  45
  46  48  49  50  51  52  53  55  56  57  59  60  61  62  63  64  66  67
  68  69  70  72  73  76  78  80  81  82  87  88  89  90  91  92  94  95
  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113
 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 130 131 133
 135 136 137 138 139 140 142 143 144 146 148 149 150 151 153 154 155 156
 157 158 159 161 163 164 166 167]

index_df_test: [  4   9  14  17  19  20  22  26  36  44  47  54  58  65  71  74  75  77
  79  83  84  85  86  93 129 132 134 141 145 147 152 160 162 165]
************
Esse é o 2 fold

index_df_train: [  0   2   3   4   6   7   8   9  10  11  13  14  15  16  17  18  19  20
  21  22  24  25  26  27  28  29  31  32  36  38  40  42  43  44  45  46
  47  48  49  50  51  53  54  55  58  59  62  63  64  65  67  68  69  71
  72  74  75  76  77  78  79  80  82  83  84  85  86  87  89  90  91  92
  93  94  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111
 112 113 114 115 116 118 120 122 123 124 125 128 129 130 131 132 134 136
 137 138 139 141 142 143 144 145 146 147 148 149 150 152 154 155 157 158
 159 160 161 162 163 165 166 167]

index_df_test: [  1   5  12  23  30  33  34  35  37  39  41  52  56  57  60  61  66  70
  73  81  88  95 117 119 121 126 127 133 135 140 151 153 156 164]
************
Esse é o 3 fold

index_df_train: [  1   3   4   5   6   8   9  11  12  13  14  15  16  17  18  19  20  21
  22  23  25  26  27  29  30  31  33  34  35  36  37  38  39  40  41  42
  43  44  45  47  52  54  56  57  58  59  60  61  62  64  65  66  68  69
  70  71  72  73  74  75  76  77  79  80  81  82  83  84  85  86  87  88
  89  90  91  93  94  95  99 100 102 104 105 106 107 109 110 112 113 115
 116 117 118 119 121 122 123 124 125 126 127 128 129 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 151 152 153 154 156 157
 158 159 160 161 162 164 165 166]

index_df_test: [  0   2   7  10  24  28  32  46  48  49  50  51  53  55  63  67  78  92
  96  97  98 101 103 108 111 114 120 130 148 149 150 155 163 167]
************
Esse é o 4 fold

index_df_train: [  0   1   2   4   5   7   9  10  11  12  13  14  15  17  19  20  22  23
  24  26  28  29  30  32  33  34  35  36  37  39  41  42  43  44  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  70  71  72  73  74  75  76  77  78  79  80  81  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98 101 103 105 108 109 110
 111 114 115 117 119 120 121 122 125 126 127 129 130 131 132 133 134 135
 136 138 140 141 142 143 144 145 146 147 148 149 150 151 152 153 155 156
 158 159 160 161 162 163 164 165 167]

index_df_test: [  3   6   8  16  18  21  25  27  31  38  40  45  68  69  82  99 100 102
 104 106 107 112 113 116 118 123 124 128 137 139 154 157 166]
************
Esse é o 5 fold

index_df_train: [  0   1   2   3   4   5   6   7   8   9  10  12  14  16  17  18  19  20
  21  22  23  24  25  26  27  28  30  31  32  33  34  35  36  37  38  39
  40  41  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  60
  61  63  65  66  67  68  69  70  71  73  74  75  77  78  79  81  82  83
  84  85  86  88  92  93  95  96  97  98  99 100 101 102 103 104 106 107
 108 111 112 113 114 116 117 118 119 120 121 123 124 126 127 128 129 130
 132 133 134 135 137 139 140 141 145 147 148 149 150 151 152 153 154 155
 156 157 160 162 163 164 165 166 167]

index_df_test: [ 11  13  15  29  42  43  59  62  64  72  76  80  87  89  90  91  94 105
 109 110 115 122 125 131 136 138 142 143 144 146 158 159 161]

In [30]:
kfold_manual_train

[array([  0,   1,   2,   3,   5,   6,   7,   8,  10,  11,  12,  13,  15,
         16,  18,  21,  23,  24,  25,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  37,  38,  39,  40,  41,  42,  43,  45,  46,  48,  49,
         50,  51,  52,  53,  55,  56,  57,  59,  60,  61,  62,  63,  64,
         66,  67,  68,  69,  70,  72,  73,  76,  78,  80,  81,  82,  87,
         88,  89,  90,  91,  92,  94,  95,  96,  97,  98,  99, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
        115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
        128, 130, 131, 133, 135, 136, 137, 138, 139, 140, 142, 143, 144,
        146, 148, 149, 150, 151, 153, 154, 155, 156, 157, 158, 159, 161,
        163, 164, 166, 167]),
 array([  0,   2,   3,   4,   6,   7,   8,   9,  10,  11,  13,  14,  15,
         16,  17,  18,  19,  20,  21,  22,  24,  25,  26,  27,  28,  29,
         31,  32,  36,  38,  40,  42,  43,  44,  45,  46,  47,  48,  49,
         50,  51,  53,  54,  55,  58,  59,  62,  63,  64,  65,  67,  68,
         69,  71,  72,  74,  75,  76,  77,  78,  79,  80,  82,  83,  84,
         85,  86,  87,  89,  90,  91,  92,  93,  94,  96,  97,  98,  99,
        100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 118, 120, 122, 123, 124, 125, 128, 129, 130,
        131, 132, 134, 136, 137, 138, 139, 141, 142, 143, 144, 145, 146,
        147, 148, 149, 150, 152, 154, 155, 157, 158, 159, 160, 161, 162,
        163, 165, 166, 167]),
 array([  1,   3,   4,   5,   6,   8,   9,  11,  12,  13,  14,  15,  16,
         17,  18,  19,  20,  21,  22,  23,  25,  26,  27,  29,  30,  31,
         33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
         47,  52,  54,  56,  57,  58,  59,  60,  61,  62,  64,  65,  66,
         68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  79,  80,  81,
         82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  93,  94,  95,
         99, 100, 102, 104, 105, 106, 107, 109, 110, 112, 113, 115, 116,
        117, 118, 119, 121, 122, 123, 124, 125, 126, 127, 128, 129, 131,
        132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
        145, 146, 147, 151, 152, 153, 154, 156, 157, 158, 159, 160, 161,
        162, 164, 165, 166]),
 array([  0,   1,   2,   4,   5,   7,   9,  10,  11,  12,  13,  14,  15,
         17,  19,  20,  22,  23,  24,  26,  28,  29,  30,  32,  33,  34,
         35,  36,  37,  39,  41,  42,  43,  44,  46,  47,  48,  49,  50,
         51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98, 101, 103, 105, 108, 109, 110, 111,
        114, 115, 117, 119, 120, 121, 122, 125, 126, 127, 129, 130, 131,
        132, 133, 134, 135, 136, 138, 140, 141, 142, 143, 144, 145, 146,
        147, 148, 149, 150, 151, 152, 153, 155, 156, 158, 159, 160, 161,
        162, 163, 164, 165, 167]),
 array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  12,  14,
         16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  44,
         45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  60,  61,  63,  65,  66,  67,  68,  69,  70,  71,  73,  74,
         75,  77,  78,  79,  81,  82,  83,  84,  85,  86,  88,  92,  93,
         95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 106, 107, 108,
        111, 112, 113, 114, 116, 117, 118, 119, 120, 121, 123, 124, 126,
        127, 128, 129, 130, 132, 133, 134, 135, 137, 139, 140, 141, 145,
        147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 160, 162,
        163, 164, 165, 166, 167])]

In [31]:
kfold_manual_test

[array([  4,   9,  14,  17,  19,  20,  22,  26,  36,  44,  47,  54,  58,
         65,  71,  74,  75,  77,  79,  83,  84,  85,  86,  93, 129, 132,
        134, 141, 145, 147, 152, 160, 162, 165]),
 array([  1,   5,  12,  23,  30,  33,  34,  35,  37,  39,  41,  52,  56,
         57,  60,  61,  66,  70,  73,  81,  88,  95, 117, 119, 121, 126,
        127, 133, 135, 140, 151, 153, 156, 164]),
 array([  0,   2,   7,  10,  24,  28,  32,  46,  48,  49,  50,  51,  53,
         55,  63,  67,  78,  92,  96,  97,  98, 101, 103, 108, 111, 114,
        120, 130, 148, 149, 150, 155, 163, 167]),
 array([  3,   6,   8,  16,  18,  21,  25,  27,  31,  38,  40,  45,  68,
         69,  82,  99, 100, 102, 104, 106, 107, 112, 113, 116, 118, 123,
        124, 128, 137, 139, 154, 157, 166]),
 array([ 11,  13,  15,  29,  42,  43,  59,  62,  64,  72,  76,  80,  87,
         89,  90,  91,  94, 105, 109, 110, 115, 122, 125, 131, 136, 138,
        142, 143, 144, 146, 158, 159, 161])]

## Resultado final

- A seguir, só estamos deixando o resultado construído em uma lista, para facilitar a execução dos testes (copiar e colar no outro caderno).

In [38]:
# Criar arrays numpy com os elementos
array1 = np.array([  0,   1,   2,   3,   5,   6,   7,   8,  10,  11,  12,  13,  15,
         16,  18,  21,  23,  24,  25,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  37,  38,  39,  40,  41,  42,  43,  45,  46,  48,  49,
         50,  51,  52,  53,  55,  56,  57,  59,  60,  61,  62,  63,  64,
         66,  67,  68,  69,  70,  72,  73,  76,  78,  80,  81,  82,  87,
         88,  89,  90,  91,  92,  94,  95,  96,  97,  98,  99, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
        115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
        128, 130, 131, 133, 135, 136, 137, 138, 139, 140, 142, 143, 144,
        146, 148, 149, 150, 151, 153, 154, 155, 156, 157, 158, 159, 161,
        163, 164, 166, 167])
array2 = np.array([  0,   2,   3,   4,   6,   7,   8,   9,  10,  11,  13,  14,  15,
         16,  17,  18,  19,  20,  21,  22,  24,  25,  26,  27,  28,  29,
         31,  32,  36,  38,  40,  42,  43,  44,  45,  46,  47,  48,  49,
         50,  51,  53,  54,  55,  58,  59,  62,  63,  64,  65,  67,  68,
         69,  71,  72,  74,  75,  76,  77,  78,  79,  80,  82,  83,  84,
         85,  86,  87,  89,  90,  91,  92,  93,  94,  96,  97,  98,  99,
        100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 118, 120, 122, 123, 124, 125, 128, 129, 130,
        131, 132, 134, 136, 137, 138, 139, 141, 142, 143, 144, 145, 146,
        147, 148, 149, 150, 152, 154, 155, 157, 158, 159, 160, 161, 162,
        163, 165, 166, 167])
array3 = np.array([  1,   3,   4,   5,   6,   8,   9,  11,  12,  13,  14,  15,  16,
         17,  18,  19,  20,  21,  22,  23,  25,  26,  27,  29,  30,  31,
         33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
         47,  52,  54,  56,  57,  58,  59,  60,  61,  62,  64,  65,  66,
         68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  79,  80,  81,
         82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  93,  94,  95,
         99, 100, 102, 104, 105, 106, 107, 109, 110, 112, 113, 115, 116,
        117, 118, 119, 121, 122, 123, 124, 125, 126, 127, 128, 129, 131,
        132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
        145, 146, 147, 151, 152, 153, 154, 156, 157, 158, 159, 160, 161,
        162, 164, 165, 166])
array4 = np.array([  0,   1,   2,   4,   5,   7,   9,  10,  11,  12,  13,  14,  15,
         17,  19,  20,  22,  23,  24,  26,  28,  29,  30,  32,  33,  34,
         35,  36,  37,  39,  41,  42,  43,  44,  46,  47,  48,  49,  50,
         51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98, 101, 103, 105, 108, 109, 110, 111,
        114, 115, 117, 119, 120, 121, 122, 125, 126, 127, 129, 130, 131,
        132, 133, 134, 135, 136, 138, 140, 141, 142, 143, 144, 145, 146,
        147, 148, 149, 150, 151, 152, 153, 155, 156, 158, 159, 160, 161,
        162, 163, 164, 165, 167])
array5 = np.array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  12,  14,
         16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  44,
         45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  60,  61,  63,  65,  66,  67,  68,  69,  70,  71,  73,  74,
         75,  77,  78,  79,  81,  82,  83,  84,  85,  86,  88,  92,  93,
         95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 106, 107, 108,
        111, 112, 113, 114, 116, 117, 118, 119, 120, 121, 123, 124, 126,
        127, 128, 129, 130, 132, 133, 134, 135, 137, 139, 140, 141, 145,
        147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 160, 162,
        163, 164, 165, 166, 167])

# Criar a lista composta
kfold_train = [array1, array2, array3, array4, array5]

In [39]:
# Criar as cinco arrays numpy
array1 = np.array([4, 9, 14, 17, 19, 20, 22, 26, 36, 44, 47, 54, 58, 65, 71, 74, 75, 77, 79, 83, 84, 85, 86, 93, 129, 132, 134, 141, 145, 147, 152, 160, 162, 165])
array2 = np.array([1, 5, 12, 23, 30, 33, 34, 35, 37, 39, 41, 52, 56, 57, 60, 61, 66, 70, 73, 81, 88, 95, 117, 119, 121, 126, 127, 133, 135, 140, 151, 153, 156, 164])
array3 = np.array([0, 2, 7, 10, 24, 28, 32, 46, 48, 49, 50, 51, 53, 55, 63, 67, 78, 92, 96, 97, 98, 101, 103, 108, 111, 114, 120, 130, 148, 149, 150, 155, 163, 167])
array4 = np.array([3, 6, 8, 16, 18, 21, 25, 27, 31, 38, 40, 45, 68, 69, 82, 99, 100, 102, 104, 106, 107, 112, 113, 116, 118, 123, 124, 128, 137, 139, 154, 157, 166])
array5 = np.array([11, 13, 15, 29, 42, 43, 59, 62, 64, 72, 76, 80, 87, 89, 90, 91, 94, 105, 109, 110, 115, 122, 125, 131, 136, 138, 142, 143, 144, 146, 158, 159, 161])

# Criar a lista composta
kfold_test = [array1, array2, array3, array4, array5]

- Verificação se foi feito corretamente

In [40]:
# Verificar se as listas são iguais elemento por elemento
sao_iguais = True

sao_iguais = all(np.array_equal(arr1, arr2) for arr1, arr2 in zip(kfold_manual_train, kfold_train))


# Imprimir o resultado
if sao_iguais:
    print("As listas são iguais elemento por elemento.")
else:
    print("As listas são diferentes em pelo menos uma posição.")

As listas são iguais elemento por elemento.

In [41]:
# Verificar se as listas são iguais elemento por elemento
sao_iguais = True

sao_iguais = all(np.array_equal(arr1, arr2) for arr1, arr2 in zip(kfold_manual_test, kfold_test))

# Imprimir o resultado
if sao_iguais:
    print("As listas são iguais elemento por elemento.")
else:
    print("As listas são diferentes em pelo menos uma posição.")

As listas são iguais elemento por elemento.